Traceback (most recent call last):
  File "patcher.py", line 1586, in <module>
    patcher = Patcher(args.run_num, args.config_path)
  File "patcher.py", line 180, in __init__
    self._load_all_dataset_metadata()
  File "patcher.py", line 292, in _load_all_dataset_metadata
    self.get_files_and_datetimes()
  File "patcher.py", line 1287, in get_files_and_datetimes
    raise Exception('No files found under given "data_start" and "data_end" settings for at least one dataset, despite files being found given your glob and regex settings. If using dates, maybe they are incorrect?')
Exception: No files found under given "data_start" and "data_end" settings for at least one dataset, despite files being found given your glob and regex settings. If using dates, maybe they are incorrect?
slurmstepd: error: acct_gather_profile/influxdb _send_data: curl_easy_perform failed to send data (discarded). Reason: Couldn't resolve host name
